title: MCP Docker Server
description: A Model Context Protocol server for Docker management with AI assistants
theme: jekyll-theme-cayman
show_downloads: true

github:
  repository_url: https://github.com/williajm/mcp_docker
  is_project_page: true

plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings

relative_links:
  enabled: true
  collections: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
