name: Coverage Badge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    name: Generate Coverage Badge
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python 3.11
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run tests with coverage
      run: |
        uv run pytest tests/unit/ \
          -v \
          --cov=mcp_docker \
          --cov-report=xml \
          --cov-report=term-missing

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
      continue-on-error: true

    - name: Generate coverage badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: .github/badges
        generate-coverage-badge: true
        coverage-badge-filename: coverage.svg

    - name: Commit badge
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .github/badges/coverage.svg || true
        git diff --staged --quiet || git commit -m "docs: Update coverage badge [skip ci]"
        git push || true
      continue-on-error: true
